sudo: false
language: android
# NBO : note that openjdk8 is not supported
jdk: oraclejdk8

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - node_modules
    - $HOME/.gradle/caches/

android:
  components:
    # to use the latest revision of Android SDK Tools
    # tools should be first in order to prevent licence not accepted errors
    - tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-26.0.0

    # The SDK version used to compile your project
    - android-25

    # Additional components
    # - extra-android-support
    # - extra-google-google_play_services
    # - extra-google-m2repository
    - extra-android-m2repository
    # - addon-google_apis-google-19

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    # - sys-img-x86-android-23
    # 23 does not work
    # - sys-img-armeabi-v7a-android-23
    - sys-img-armeabi-v7a-android-21

  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - '.+'                              # accept all licences

env:
  global:
    - ADB_INSTALL_TIMEOUT=8 # minutes (2 minutes by default)

install :
  # force acceptance of licence for constraint layout
  - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2"
  - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"

# Emulator Management: Create, Start and Wait
before_script:
  - echo no | android create avd --force --name test --target android-21 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window -gpu off -no-boot-anim&
  - android-wait-for-emulator
  - adb devices
  - adb shell input keyevent 82 &

script:
  - echo $ADB_INSTALL_TIMEOUT
  - android list target
  # - ./gradlew connectedAndroidTest -PdisablePreDex
  # see : http://stackoverflow.com/questions/32952413/gradle-commands-fail-on-api-23-google-api-emulator-image-armeabi-v7a
  - ./gradlew clean
  - ./gradlew assembleDebug
  - ./gradlew assembleDebugAndroidTest
  - adb install app/build/outputs/apk/app-debug.apk
  - adb install app/build/outputs/apk/app-debug-androidTest.apk